server:
  port: 4145

spring:
  flyway:
    enabled: false

  application:
    name: NexoraAcademy

  profiles:
    active: dev

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173