apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexora-app
  namespace: nexora-academy
  labels:
    app: nexora-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nexora-app
  template:
    metadata:
      labels:
        app: nexora-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: app
          image: nexora-academy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          envFrom:
            - configMapRef:
                name: nexora-config
            - secretRef:
                name: nexora-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}
